################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
board \
bt_ble/bluetooth/export/extension \
bt_ble/bluetooth/export/vendor \
bt_ble/port/osal/src/freertos \
bt_ble/port/pal/mcux \
bt_ble/port/pal/mcux/bluetooth \
bt_ble/port/pal/mcux/bluetooth/controller \
bt_ble/port/pal/mcux/ethal \
bt_ble/port/pal/mcux/toolspec/mcuxpresso \
bt_ble/source/impl/ethermind \
bt_ble/source/impl/ethermind/platform \
component/conn_fwloader \
component/conn_fwloader/fw_bin/rw61x \
component/devices/RW612 \
component/els_pkc/src/comps/mcuxClAead/src \
component/els_pkc/src/comps/mcuxClAeadModes/src \
component/els_pkc/src/comps/mcuxClAes/src \
component/els_pkc/src/comps/mcuxClBuffer/src \
component/els_pkc/src/comps/mcuxClCipher/src \
component/els_pkc/src/comps/mcuxClCipherModes/src \
component/els_pkc/src/comps/mcuxClEcc/src \
component/els_pkc/src/comps/mcuxClEls/src \
component/els_pkc/src/comps/mcuxClHash/src \
component/els_pkc/src/comps/mcuxClHashModes/src \
component/els_pkc/src/comps/mcuxClHmac/src \
component/els_pkc/src/comps/mcuxClKey/src \
component/els_pkc/src/comps/mcuxClMac/src \
component/els_pkc/src/comps/mcuxClMacModes/src \
component/els_pkc/src/comps/mcuxClMath/src \
component/els_pkc/src/comps/mcuxClMemory/src \
component/els_pkc/src/comps/mcuxClPadding/src \
component/els_pkc/src/comps/mcuxClPkc/src \
component/els_pkc/src/comps/mcuxClPrng/src \
component/els_pkc/src/comps/mcuxClRandom/src \
component/els_pkc/src/comps/mcuxClRandomModes/src \
component/els_pkc/src/comps/mcuxClRsa/src \
component/els_pkc/src/comps/mcuxClSession/src \
component/els_pkc/src/comps/mcuxClTrng/src \
component/els_pkc/src/comps/mcuxCsslMemory/src \
component/els_pkc/src/comps/mcuxCsslParamIntegrity/src \
component/els_pkc/src/platforms/rw61x \
component/imu_adapter \
component/lists \
component/log \
component/mem_manager \
component/messaging \
component/osa \
component/power_manager \
component/rng \
component/serial_manager \
component/time_stamp \
component/timer \
component/timer_manager \
component/uart \
device \
drivers \
edgefast/bluetooth/porting \
edgefast/bluetooth/source/impl/ethermind/common \
edgefast/bluetooth/source/impl/ethermind/crypto \
edgefast/bluetooth/source/impl/ethermind/host \
edgefast/bluetooth/source/porting/fifo \
edgefast/bluetooth/source/porting/lifo \
edgefast/bluetooth/source/porting/net \
edgefast/bluetooth/source/porting/poll \
edgefast/bluetooth/source/porting \
edgefast/bluetooth/source/porting/queue \
edgefast/bluetooth/source/porting/sem \
edgefast/bluetooth/source/porting/slab \
edgefast/bluetooth/source/porting/slist \
edgefast/bluetooth/source/porting/thread \
edgefast/bluetooth/source/porting/work \
edgefast/bluetooth/source/services \
fatfs/source \
fatfs/source/fsl_usb_disk \
flash/mflash/frdmrw612 \
flash/mflash \
flash_config \
framework/platform/rw61x \
framework/services/LowPower \
freertos/freertos-kernel \
freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure \
freertos/freertos-kernel/portable/MemMang \
littlefs \
mbedtls/library \
mbedtls/port/els \
mbedtls/port/pkc \
source \
startup \
usb/host/class \
usb/host \
utilities/debug_console \
utilities \
utilities/str \

