/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: RW612
package_id: RW612ETA2I
mcu_data: ksdk2_0
processor_version: 25.06.10
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_io_mux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: E5, peripheral: FLEXCOMM3, signal: USART_RXD, pin_signal: GPIO_24}
  - {pin_num: L9, peripheral: FLEXCOMM1, signal: SPI_SCK, pin_signal: GPIO_7, pull_up_down: disable}
  - {pin_num: M4, peripheral: FLEXCOMM1, signal: SPI_MOSI, pin_signal: GPIO_9, pull_up_down: disable}
  - {pin_num: M6, peripheral: FLEXCOMM1, signal: SPI_MISO, pin_signal: GPIO_8, pull_up_down: disable}
  - {pin_num: L7, peripheral: GPIO, signal: 'PIO0, 5', pin_signal: GPIO_5}
  - {pin_num: F8, peripheral: GPIO, signal: 'PIO0, 4', pin_signal: GPIO_4}
  - {pin_num: M3, peripheral: GPIO, signal: 'PIO0, 10', pin_signal: GPIO_10}
  - {pin_num: H3, peripheral: GPIO, signal: 'PIO0, 15', pin_signal: GPIO_15}
  - {pin_num: M1, peripheral: GPIO, signal: 'PIO0, 0', pin_signal: GPIO_0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : 
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
    /* Initialize FC1_SPI_SS0 functionality on pin GPIO_7, GPIO_9, GPIO_8 (pin L9_M4_M6) */
    IO_MUX_SetPinMux(IO_MUX_FC1_SPI_SS0);
    /* Initialize FC3_USART_DATA functionality on pin GPIO_24 (pin E5) */
    IO_MUX_SetPinMux(IO_MUX_FC3_USART_DATA);
    /* Initialize GPIO0 functionality on pin GPIO_0 (pin M1) */
    IO_MUX_SetPinMux(IO_MUX_GPIO0);
    /* Initialize GPIO4 functionality on pin GPIO_4 (pin F8) */
    IO_MUX_SetPinMux(IO_MUX_GPIO4);
    /* Initialize GPIO5 functionality on pin GPIO_5 (pin L7) */
    IO_MUX_SetPinMux(IO_MUX_GPIO5);
    /* Initialize GPIO10 functionality on pin GPIO_10 (pin M3) */
    IO_MUX_SetPinMux(IO_MUX_GPIO10);
    /* Initialize GPIO15 functionality on pin GPIO_15 (pin H3) */
    IO_MUX_SetPinMux(IO_MUX_GPIO15);
    /* Set GPIO_7 (pin L9_M4_M6) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(7U, IO_MUX_PinConfigNoPull);
    /* Set GPIO_8 (pin L9_M4_M6) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(8U, IO_MUX_PinConfigNoPull);
    /* Set GPIO_9 (pin L9_M4_M6) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(9U, IO_MUX_PinConfigNoPull);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
